### ISSUE TITLE
breaks updating a 5i25 on an amd64

### ISSUE THREAD

**Issue by mhaberler** [micges/mesaflash#4] opened 2015-06-17 17:54 UTC
seems to be a x86 vs amd64 issue - same card:

amd64:

````
root@amd64:/home/mah/external-clocking# mesaflash --device 5i25 --verbose --verify 7i76x2d.bit
Checking file... OK
  File type: BIT file
  Design name: TopPCIHostMot2.ncd;UserID=0xFFFFFFFF
  Part name: 6slx9tqg144
  Design date: 2015/06/16
  Design time: 17:20:45
  Config Length: 340604
Error: BootSector is invalid
`````

x86:

````
root@dumpster:/home/mah/external-clocking# mesaflash --device 5i25 --verbose --write 7i76x2d.bit
Checking file... OK
  File type: BIT file
  Design name: TopPCIHostMot2.ncd;UserID=0xFFFFFFFF
  Part name: 6slx9tqg144
  Design date: 2015/06/16
  Design time: 17:20:45
  Config Length: 340604
Boot sector OK
EEPROM sectors to write: 6, max sectors in area: 8
Erasing EEPROM sectors starting from 0x80000...
  |EEEEEE
  Erasing time: 3.43 seconds
Programming EEPROM sectors starting from 0x80000...
  |WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
  Programming time: 1.616 seconds
Board configuration updated successfully.

You must power cycle board or use --reload command to load updated firmware.
````

**Comment by jepler** [comment] 2015-06-18 19:04
Not reproduced here, but my setup is not identical to yours.

* 6i24 (instead of 5i25)
* Debian Wheezy (instead of unspecified)
* At mesaflash ref b1b0882 (instead of unspecified)

```
$ sudo ./mesaflash --device 5i24 --verify SVST8_4.BIT 
Checking file... OK
  File type: BIT file
Boot sector OK
Verifying EEPROM sectors starting from 0x100000...
```
(verification then fails but that's because I didn't bother matching the bitfile already on the device)

Please provide any additional information you can to allow me to reproduce the problem.

It seems most likely that the problem is also card-dependent, so I may not be able to offer any further assistance diagnosing this.

**Comment by micges** [comment] 2015-08-14 21:23
Michael, is it still happening on amd64 or it was some flashing error?

**Comment by mhaberler** [comment] 2015-08-15 14:10
I have not tried since - flashed on the x86 and was done with it
do you need a retry?

**Comment by micges** [comment] 2015-08-15 21:17
yeah, if you have near amd64 setup

**Comment by sirop** [comment] 2015-10-14 13:27
Just tried your mesaflash  on my Intel 64 bit NUC:
```
mesaflash-git$ sudo ./mesaflash  --device 5I25 --write ../../../configs/hostmot2/cps5i25.bit
Checking file... OK
  File type: BIT file
Boot sector OK
EEPROM sectors to write: 6, max sectors in area: 16
Erasing EEPROM sectors starting from 0x100000...
  |EEEEEE
Programming EEPROM sectors starting from 0x100000...
  |WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
Board configuration updated successfully.

You must power cycle board or use --reload command to load updated firmware.
```
Seems to work as:
```
mesaflash-git$ sudo more /var/log/syslog | grep IO
....................
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2_pci: loading Mesa AnyIO HostMot2 driver version 0.7
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 000 (P3-01): PWMGen #0, pin Out0 (PWM or Up) (Output)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 001 (P3-14): IOPort
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 002 (P3-02): IOPort
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 003 (P3-15): IOPort
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 004 (P3-03): IOPort
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 005 (P3-16): IOPort
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 006 (P3-04): StepGen #1, pin Direction (Output)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 007 (P3-17): IOPort
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 008 (P3-05): StepGen #1, pin Step (Output)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 009 (P3-06): StepGen #2, pin Direction (Output)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 010 (P3-07): StepGen #2, pin Step (Output)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 011 (P3-08): StepGen #3, pin Direction (Output)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 012 (P3-09): StepGen #3, pin Step (Output)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 013 (P3-10): IOPort
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 014 (P3-11): Encoder #0, pin B (Input)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 015 (P3-12): Encoder #0, pin A (Input)
Oct 14 07:47:32 debian-cml2 msgd:0: hal_lib:4019:rt hm2/hm2_5i25.0:     IO Pin 016 (P3-13): Encoder #0, pin Index (Input)
.........................
```
which corresponds to the firmware changed by me.  

Yes, I used `--reload` option instead of power cycling.

**Comment by sirop** [comment] 2015-10-14 13:36
One addition: I have a 6i25 card with 5i25 firmware.

**Comment by jepler** [comment] 2016-07-01 11:56
@micges please accept #12 so we can close this issue

**Closed** 2016-07-01 12:35 UTC
